// Generated by CIRCT firtool-1.128.0
module AddRawFN(	// src/main/scala/AddRecFN.scala:47:7
  input         io_a_isNaN,	// src/main/scala/AddRecFN.scala:49:16
                io_a_isInf,	// src/main/scala/AddRecFN.scala:49:16
                io_a_isZero,	// src/main/scala/AddRecFN.scala:49:16
                io_a_sign,	// src/main/scala/AddRecFN.scala:49:16
  input  [6:0]  io_a_sExp,	// src/main/scala/AddRecFN.scala:49:16
  input  [11:0] io_a_sig,	// src/main/scala/AddRecFN.scala:49:16
  input         io_b_isNaN,	// src/main/scala/AddRecFN.scala:49:16
                io_b_isInf,	// src/main/scala/AddRecFN.scala:49:16
                io_b_isZero,	// src/main/scala/AddRecFN.scala:49:16
                io_b_sign,	// src/main/scala/AddRecFN.scala:49:16
  input  [6:0]  io_b_sExp,	// src/main/scala/AddRecFN.scala:49:16
  input  [11:0] io_b_sig,	// src/main/scala/AddRecFN.scala:49:16
  output        io_invalidExc,	// src/main/scala/AddRecFN.scala:49:16
                io_rawOut_isNaN,	// src/main/scala/AddRecFN.scala:49:16
                io_rawOut_isInf,	// src/main/scala/AddRecFN.scala:49:16
                io_rawOut_isZero,	// src/main/scala/AddRecFN.scala:49:16
                io_rawOut_sign,	// src/main/scala/AddRecFN.scala:49:16
  output [6:0]  io_rawOut_sExp,	// src/main/scala/AddRecFN.scala:49:16
  output [13:0] io_rawOut_sig	// src/main/scala/AddRecFN.scala:49:16
);

  wire [6:0]  _sDiffExps_T = io_a_sExp - io_b_sExp;	// src/main/scala/AddRecFN.scala:63:31
  wire        _common_sExpOut_T = $signed(_sDiffExps_T) < 7'sh0;	// src/main/scala/AddRecFN.scala:63:31, :64:41, :95:{45,49,98}
  wire [3:0]  _modNatAlignDist_T_4 =
    _common_sExpOut_T ? io_b_sExp[3:0] - io_a_sExp[3:0] : _sDiffExps_T[3:0];	// src/main/scala/AddRecFN.scala:49:16, :63:31, :64:{30,41,58}
  wire        isMaxAlign =
    (|(_sDiffExps_T[6:4])) & (_sDiffExps_T[6:4] != 3'h7 | _sDiffExps_T[3:0] == 4'h0);	// src/main/scala/AddRecFN.scala:63:31, :66:{19,37,45}, :67:{42,51,63,87}
  wire [3:0]  alignDist = isMaxAlign ? 4'hF : _modNatAlignDist_T_4;	// src/main/scala/AddRecFN.scala:64:30, :66:45, :68:24
  wire        far_subMags = io_a_sign != io_b_sign;	// src/main/scala/AddRecFN.scala:61:29, :69:24
  wire        closeSubMags = far_subMags & ~isMaxAlign & _modNatAlignDist_T_4 < 4'h2;	// src/main/scala/AddRecFN.scala:61:29, :64:30, :66:45, :69:{24,33,36,48,68}
  wire        _close_alignedSigA_T_5 = $signed(_sDiffExps_T) > -7'sh1;	// src/main/scala/AddRecFN.scala:63:31, :73:18
  wire [13:0] _close_alignedSigA_T_4 =
    _close_alignedSigA_T_5 & _sDiffExps_T[0] ? {io_a_sig, 2'h0} : 14'h0;	// src/main/scala/AddRecFN.scala:63:31, :73:{12,18,32,45,58}
  wire [12:0] _GEN =
    _close_alignedSigA_T_4[12:0]
    | (_close_alignedSigA_T_5 & ~(_sDiffExps_T[0]) ? {io_a_sig, 1'h0} : 13'h0);	// src/main/scala/AddRecFN.scala:63:31, :73:{12,18,45,68}, :74:{12,32,35,58}
  wire [13:0] _close_sSigSum_T_3 =
    {_close_alignedSigA_T_4[13],
     _GEN[12],
     _GEN[11:0] | (_common_sExpOut_T ? io_a_sig : 12'h0)}
    - {io_b_sig[11], io_b_sig, 1'h0};	// src/main/scala/AddRecFN.scala:64:41, :73:{12,68}, :74:68, :75:12, :76:50
  wire        _close_notTotalCancellation_signOut_T =
    $signed(_close_sSigSum_T_3) < 14'sh0;	// src/main/scala/AddRecFN.scala:76:50, :77:42
  wire [12:0] _close_sigSum_T_4 =
    _close_notTotalCancellation_signOut_T
      ? 13'h0 - _close_sSigSum_T_3[12:0]
      : _close_sSigSum_T_3[12:0];	// src/main/scala/AddRecFN.scala:76:50, :77:{27,42,49}
  wire [2:0]  close_normDistReduced2 =
    (|(_close_sigSum_T_4[12:11]))
      ? 3'h0
      : (|(_close_sigSum_T_4[10:9]))
          ? 3'h1
          : (|(_close_sigSum_T_4[8:7]))
              ? 3'h2
              : (|(_close_sigSum_T_4[6:5]))
                  ? 3'h3
                  : (|(_close_sigSum_T_4[4:3]))
                      ? 3'h4
                      : (|(_close_sigSum_T_4[2:1])) ? 3'h5 : 3'h6;	// src/main/scala/AddRecFN.scala:77:27, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/primitives.scala:103:{33,54}, :106:{15,57}
  wire [27:0] _close_sigOut_T =
    {15'h0, _close_sigSum_T_4} << {24'h0, close_normDistReduced2, 1'h0};	// src/main/scala/AddRecFN.scala:77:{27,49}, :82:38, src/main/scala/chisel3/util/Mux.scala:58:84
  wire [10:0] _far_sigSmaller_T_1 = _common_sExpOut_T ? io_a_sig[10:0] : io_b_sig[10:0];	// src/main/scala/AddRecFN.scala:49:16, :64:41, :89:29
  wire [15:0] far_mainAlignedSigSmaller = {_far_sigSmaller_T_1, 5'h0} >> alignDist;	// src/main/scala/AddRecFN.scala:68:24, :89:29, :90:{52,56}
  wire [4:0]  far_roundExtraMask_shift = $signed(5'sh10 >>> alignDist[3:2]);	// src/main/scala/AddRecFN.scala:68:24, :92:47, src/main/scala/primitives.scala:76:56
  wire [6:0]  _GEN_0 =
    {far_mainAlignedSigSmaller[2:0],
     {_far_sigSmaller_T_1[10],
      |(_far_sigSmaller_T_1[9:6]),
      |(_far_sigSmaller_T_1[5:2]),
      |(_far_sigSmaller_T_1[1:0])}
       & {far_roundExtraMask_shift[0],
          far_roundExtraMask_shift[1],
          far_roundExtraMask_shift[2],
          far_roundExtraMask_shift[3]}};	// src/main/scala/AddRecFN.scala:89:29, :90:56, :95:{38,45,49,76,98}, src/main/scala/primitives.scala:76:56, :77:20, :78:22, :120:{33,54}, :123:15, :124:20
  wire        _GEN_1 = io_a_sign == io_b_sign;	// src/main/scala/AddRecFN.scala:61:29, :69:24, :97:39
  wire [14:0] _far_sigSum_T_3 =
    {1'h0, _common_sExpOut_T ? io_b_sig[10:0] : io_a_sig[10:0], 3'h0}
    + (_GEN_1
         ? {1'h0, far_mainAlignedSigSmaller[15:3], |_GEN_0}
         : {1'h1, ~{far_mainAlignedSigSmaller[15:3], |_GEN_0}}) + {14'h0, far_subMags};	// src/main/scala/AddRecFN.scala:49:16, :61:29, :64:41, :69:24, :88:29, :90:56, :94:{12,38}, :95:{45,49,98}, :97:{39,56,62}, :98:{41,68}
  wire        notNaN_isInfOut = io_a_isInf | io_b_isInf;	// src/main/scala/AddRecFN.scala:103:38
  wire        addZeros = io_a_isZero & io_b_isZero;	// src/main/scala/AddRecFN.scala:104:32
  wire        notNaN_specialCase = notNaN_isInfOut | addZeros;	// src/main/scala/AddRecFN.scala:103:38, :104:32, :105:46
  assign io_invalidExc =
    io_a_isNaN & ~(io_a_sig[9]) | io_b_isNaN & ~(io_b_sig[9]) | io_a_isInf & io_b_isInf
    & far_subMags;	// src/main/scala/AddRecFN.scala:47:7, :61:29, :69:24, :102:{43,57}, :121:{45,71}, src/main/scala/common.scala:82:{46,49,56}
  assign io_rawOut_isNaN = io_a_isNaN | io_b_isNaN;	// src/main/scala/AddRecFN.scala:47:7, :125:35
  assign io_rawOut_isInf = notNaN_isInfOut;	// src/main/scala/AddRecFN.scala:47:7, :103:38
  assign io_rawOut_isZero =
    addZeros | ~notNaN_isInfOut & closeSubMags & ~(|(_close_sigOut_T[12:11]));	// src/main/scala/AddRecFN.scala:47:7, :69:{33,48}, :82:{38,63}, :83:{35,49,82}, :103:38, :104:32, :106:{37,41,58,74}
  assign io_rawOut_sign =
    io_a_sign == io_b_sign & io_a_sign | io_a_isInf & io_a_sign | io_b_isInf & io_b_sign
    | ~notNaN_specialCase & closeSubMags & (|(_close_sigOut_T[12:11]))
    & (io_a_sign ^ _close_notTotalCancellation_signOut_T) | ~notNaN_specialCase
    & ~closeSubMags & (_common_sExpOut_T ? io_b_sign : io_a_sign);	// src/main/scala/AddRecFN.scala:47:7, :61:29, :64:41, :69:{33,48}, :77:42, :82:{38,63}, :83:{49,82}, :84:56, :87:26, :105:46, :108:{39,63}, :109:{39,63}, :110:39, :111:63, :112:{10,30,46}, :113:{38,77}, :114:{30,33,47}
  assign io_rawOut_sExp =
    (closeSubMags | _common_sExpOut_T ? io_b_sExp : io_a_sExp)
    - {3'h0, closeSubMags ? {close_normDistReduced2, 1'h0} : {3'h0, far_subMags}};	// src/main/scala/AddRecFN.scala:47:7, :61:29, :64:41, :69:{24,33,48}, :81:53, :116:{13,27}, :117:{13,18}, src/main/scala/chisel3/util/Mux.scala:58:84
  assign io_rawOut_sig =
    closeSubMags
      ? {_close_sigOut_T[12:0], 1'h0}
      : _GEN_1
          ? {_far_sigSum_T_3[14:2], _far_sigSum_T_3[1] | _far_sigSum_T_3[0]}
          : _far_sigSum_T_3[13:0];	// src/main/scala/AddRecFN.scala:47:7, :61:29, :69:{24,33,48}, :82:{38,63}, :97:39, :98:{41,68}, :99:{25,62,67,79}, :118:28
endmodule

