// Generated by CIRCT firtool-1.128.0
module AddRecFN(	// src/main/scala/AddRecFN.scala:133:7
  input  [16:0] io_a,	// src/main/scala/AddRecFN.scala:135:16
                io_b,	// src/main/scala/AddRecFN.scala:135:16
  output [16:0] io_out	// src/main/scala/AddRecFN.scala:135:16
);

  wire        _addRawFN_io_invalidExc;	// src/main/scala/AddRecFN.scala:147:26
  wire        _addRawFN_io_rawOut_isNaN;	// src/main/scala/AddRecFN.scala:147:26
  wire        _addRawFN_io_rawOut_isInf;	// src/main/scala/AddRecFN.scala:147:26
  wire        _addRawFN_io_rawOut_isZero;	// src/main/scala/AddRecFN.scala:147:26
  wire        _addRawFN_io_rawOut_sign;	// src/main/scala/AddRecFN.scala:147:26
  wire [6:0]  _addRawFN_io_rawOut_sExp;	// src/main/scala/AddRecFN.scala:147:26
  wire [13:0] _addRawFN_io_rawOut_sig;	// src/main/scala/AddRecFN.scala:147:26
  AddRawFN addRawFN (	// src/main/scala/AddRecFN.scala:147:26
    .io_a_isNaN       ((&(io_a[15:14])) & io_a[13]),	// src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}
    .io_a_isInf       ((&(io_a[15:14])) & ~(io_a[13])),	// src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}
    .io_a_isZero      (~(|(io_a[15:13]))),	// src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}
    .io_a_sign        (io_a[16]),	// src/main/scala/rawFloatFromRecFN.scala:59:25
    .io_a_sExp        ({1'h0, io_a[15:10]}),	// src/main/scala/rawFloatFromRecFN.scala:51:21, :60:27
    .io_a_sig         ({1'h0, |(io_a[15:13]), io_a[9:0]}),	// src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, :61:{44,49}
    .io_b_isNaN       ((&(io_b[15:14])) & io_b[13]),	// src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}
    .io_b_isInf       ((&(io_b[15:14])) & ~(io_b[13])),	// src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}
    .io_b_isZero      (~(|(io_b[15:13]))),	// src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}
    .io_b_sign        (io_b[16]),	// src/main/scala/rawFloatFromRecFN.scala:59:25
    .io_b_sExp        ({1'h0, io_b[15:10]}),	// src/main/scala/rawFloatFromRecFN.scala:51:21, :60:27
    .io_b_sig         ({1'h0, |(io_b[15:13]), io_b[9:0]}),	// src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, :61:{44,49}
    .io_invalidExc    (_addRawFN_io_invalidExc),
    .io_rawOut_isNaN  (_addRawFN_io_rawOut_isNaN),
    .io_rawOut_isInf  (_addRawFN_io_rawOut_isInf),
    .io_rawOut_isZero (_addRawFN_io_rawOut_isZero),
    .io_rawOut_sign   (_addRawFN_io_rawOut_sign),
    .io_rawOut_sExp   (_addRawFN_io_rawOut_sExp),
    .io_rawOut_sig    (_addRawFN_io_rawOut_sig)
  );	// src/main/scala/AddRecFN.scala:147:26
  RoundRawFNToRecFN_e5_s11 roundRawFNToRecFN (	// src/main/scala/AddRecFN.scala:157:15
    .io_invalidExc (_addRawFN_io_invalidExc),	// src/main/scala/AddRecFN.scala:147:26
    .io_in_isNaN   (_addRawFN_io_rawOut_isNaN),	// src/main/scala/AddRecFN.scala:147:26
    .io_in_isInf   (_addRawFN_io_rawOut_isInf),	// src/main/scala/AddRecFN.scala:147:26
    .io_in_isZero  (_addRawFN_io_rawOut_isZero),	// src/main/scala/AddRecFN.scala:147:26
    .io_in_sign    (_addRawFN_io_rawOut_sign),	// src/main/scala/AddRecFN.scala:147:26
    .io_in_sExp    (_addRawFN_io_rawOut_sExp),	// src/main/scala/AddRecFN.scala:147:26
    .io_in_sig     (_addRawFN_io_rawOut_sig),	// src/main/scala/AddRecFN.scala:147:26
    .io_out        (io_out)
  );	// src/main/scala/AddRecFN.scala:157:15
endmodule

