// Generated by CIRCT firtool-1.128.0
module RoundAnyRawFNToRecFN_ie5_is13_oe5_os11(	// src/main/scala/RoundAnyRawFNToRecFN.scala:48:5
  input         io_invalidExc,	// src/main/scala/RoundAnyRawFNToRecFN.scala:58:16
                io_in_isNaN,	// src/main/scala/RoundAnyRawFNToRecFN.scala:58:16
                io_in_isInf,	// src/main/scala/RoundAnyRawFNToRecFN.scala:58:16
                io_in_isZero,	// src/main/scala/RoundAnyRawFNToRecFN.scala:58:16
                io_in_sign,	// src/main/scala/RoundAnyRawFNToRecFN.scala:58:16
  input  [6:0]  io_in_sExp,	// src/main/scala/RoundAnyRawFNToRecFN.scala:58:16
  input  [13:0] io_in_sig,	// src/main/scala/RoundAnyRawFNToRecFN.scala:58:16
  output [16:0] io_out	// src/main/scala/RoundAnyRawFNToRecFN.scala:58:16
);

  wire [64:0] roundMask_shift = $signed(65'sh10000000000000000 >>> ~(io_in_sExp[5:0]));	// src/main/scala/RoundAnyRawFNToRecFN.scala:156:37, src/main/scala/primitives.scala:52:21, :76:56
  wire [7:0]  _roundMask_T_12 =
    {4'h0, roundMask_shift[14:11]} | {roundMask_shift[10:7], 4'h0};	// src/main/scala/primitives.scala:76:56, :77:20, :78:22
  wire [7:0]  _roundMask_T_22 =
    {2'h0, _roundMask_T_12[7:2] & 6'h33} | {_roundMask_T_12[5:0] & 6'h33, 2'h0};	// src/main/scala/primitives.scala:77:20
  wire [7:0]  _roundMask_T_32 =
    {1'h0, _roundMask_T_22[7:1] & 7'h55} | {_roundMask_T_22[6:0] & 7'h55, 1'h0};	// src/main/scala/primitives.scala:77:20
  wire        _common_underflow_T_4 = roundMask_shift[18] | io_in_sig[13];	// src/main/scala/RoundAnyRawFNToRecFN.scala:120:57, :159:23, src/main/scala/primitives.scala:76:56, :77:20, :78:22
  wire [12:0] _GEN =
    {_roundMask_T_32,
     roundMask_shift[15],
     roundMask_shift[16],
     roundMask_shift[17],
     _common_underflow_T_4,
     1'h1};	// src/main/scala/RoundAnyRawFNToRecFN.scala:159:{23,42}, src/main/scala/primitives.scala:76:56, :77:20, :78:22
  wire [12:0] _roundPosBit_T =
    io_in_sig[13:1]
    & {1'h1,
       ~_roundMask_T_32,
       ~(roundMask_shift[15]),
       ~(roundMask_shift[16]),
       ~(roundMask_shift[17]),
       ~_common_underflow_T_4} & _GEN;	// src/main/scala/RoundAnyRawFNToRecFN.scala:58:16, :159:{23,42}, :162:53, :163:{28,46}, :164:40, src/main/scala/primitives.scala:76:56, :77:20, :78:22
  wire [12:0] roundedSig =
    (|_roundPosBit_T)
      ? {1'h0,
         io_in_sig[13:2]
           | {_roundMask_T_32,
              roundMask_shift[15],
              roundMask_shift[16],
              roundMask_shift[17],
              _common_underflow_T_4}} + 13'h1
        & ~((|_roundPosBit_T) & (io_in_sig[12:0] & _GEN) == 13'h0
              ? {_roundMask_T_32,
                 roundMask_shift[15],
                 roundMask_shift[16],
                 roundMask_shift[17],
                 _common_underflow_T_4,
                 1'h1}
              : 13'h0)
      : {1'h0,
         io_in_sig[13:2]
           & {~_roundMask_T_32,
              ~(roundMask_shift[15]),
              ~(roundMask_shift[16]),
              ~(roundMask_shift[17]),
              ~_common_underflow_T_4}};	// src/main/scala/RoundAnyRawFNToRecFN.scala:58:16, :159:{23,42}, :163:{28,46}, :164:{40,56}, :165:{42,62}, :173:16, :174:{32,49,57}, :175:{21,25,64}, :177:35, :180:{30,43,47}, src/main/scala/primitives.scala:76:56, :77:20, :78:22
  wire [7:0]  sRoundedExp = {io_in_sExp[6], io_in_sExp} + {6'h0, roundedSig[12:11]};	// src/main/scala/RoundAnyRawFNToRecFN.scala:173:16, :185:{40,54}
  wire        common_totalUnderflow = $signed(sRoundedExp) < 8'sh8;	// src/main/scala/RoundAnyRawFNToRecFN.scala:185:40, :200:31
  wire        isNaNOut = io_invalidExc | io_in_isNaN;	// src/main/scala/RoundAnyRawFNToRecFN.scala:235:34
  wire        notNaN_isInfOut =
    io_in_isInf | ~isNaNOut & ~io_in_isInf & ~io_in_isZero
    & $signed(sRoundedExp[7:4]) > 4'sh2;	// src/main/scala/RoundAnyRawFNToRecFN.scala:185:40, :196:{30,50}, :235:34, :237:{22,33,36,61,64}, :238:32, :248:32
  assign io_out =
    {~isNaNOut & io_in_sign,
     sRoundedExp[5:0] & ~(io_in_isZero | common_totalUnderflow ? 6'h38 : 6'h0)
       & {2'h3, ~notNaN_isInfOut, 3'h7} | (notNaN_isInfOut ? 6'h30 : 6'h0)
       | (isNaNOut ? 6'h38 : 6'h0),
     isNaNOut | io_in_isZero | common_totalUnderflow
       ? {isNaNOut, 9'h0}
       : io_in_sig[13] ? roundedSig[10:1] : roundedSig[9:0]};	// src/main/scala/RoundAnyRawFNToRecFN.scala:48:5, :120:57, :173:16, :185:40, :187:37, :189:16, :190:27, :191:27, :200:31, :235:34, :248:32, :250:22, :252:24, :253:{14,18,32}, :264:17, :265:{14,18}, :276:15, :277:{16,73}, :278:16, :280:{12,22,38}, :281:16, :286:33
endmodule

