// Generated by CIRCT firtool-1.128.0
module RoundRawFNToRecFN_e5_s11(	// src/main/scala/RoundAnyRawFNToRecFN.scala:295:5
  input         io_invalidExc,	// src/main/scala/RoundAnyRawFNToRecFN.scala:299:16
                io_in_isNaN,	// src/main/scala/RoundAnyRawFNToRecFN.scala:299:16
                io_in_isInf,	// src/main/scala/RoundAnyRawFNToRecFN.scala:299:16
                io_in_isZero,	// src/main/scala/RoundAnyRawFNToRecFN.scala:299:16
                io_in_sign,	// src/main/scala/RoundAnyRawFNToRecFN.scala:299:16
  input  [6:0]  io_in_sExp,	// src/main/scala/RoundAnyRawFNToRecFN.scala:299:16
  input  [13:0] io_in_sig,	// src/main/scala/RoundAnyRawFNToRecFN.scala:299:16
  output [16:0] io_out	// src/main/scala/RoundAnyRawFNToRecFN.scala:299:16
);

  RoundAnyRawFNToRecFN_ie5_is13_oe5_os11 roundAnyRawFNToRecFN (	// src/main/scala/RoundAnyRawFNToRecFN.scala:310:15
    .io_invalidExc (io_invalidExc),
    .io_in_isNaN   (io_in_isNaN),
    .io_in_isInf   (io_in_isInf),
    .io_in_isZero  (io_in_isZero),
    .io_in_sign    (io_in_sign),
    .io_in_sExp    (io_in_sExp),
    .io_in_sig     (io_in_sig),
    .io_out        (io_out)
  );	// src/main/scala/RoundAnyRawFNToRecFN.scala:310:15
endmodule

