// Generated by CIRCT firtool-1.128.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TinyGPU(	// src/main/scala/TinyGPU.scala:17:7
  input         clock,	// src/main/scala/TinyGPU.scala:17:7
                reset,	// src/main/scala/TinyGPU.scala:17:7
  input  [7:0]  io_ui_in,	// src/main/scala/TinyGPU.scala:18:14
  output [7:0]  io_uo_out,	// src/main/scala/TinyGPU.scala:18:14
  input  [5:0]  io_address,	// src/main/scala/TinyGPU.scala:18:14
  input  [31:0] io_data_in,	// src/main/scala/TinyGPU.scala:18:14
  input  [1:0]  io_data_write_n,	// src/main/scala/TinyGPU.scala:18:14
                io_data_read_n,	// src/main/scala/TinyGPU.scala:18:14
  output [31:0] io_data_out,	// src/main/scala/TinyGPU.scala:18:14
  output        io_data_ready,	// src/main/scala/TinyGPU.scala:18:14
                io_user_interrupt	// src/main/scala/TinyGPU.scala:18:14
);

  wire [16:0] _addRecFN_io_out;	// src/main/scala/TinyGPU.scala:74:24
  reg  [31:0] example_data;	// src/main/scala/TinyGPU.scala:30:29
  wire        _io_data_out_T = io_address == 6'h0;	// src/main/scala/TinyGPU.scala:37:17
  reg         example_interrupt;	// src/main/scala/TinyGPU.scala:53:34
  reg         last_ui_in_6;	// src/main/scala/TinyGPU.scala:54:29
  reg  [15:0] add_a;	// src/main/scala/TinyGPU.scala:67:22
  reg  [15:0] add_b;	// src/main/scala/TinyGPU.scala:68:22
  wire        addRecFN_io_a_rawIn_isZeroExpIn = add_a[14:10] == 5'h0;	// src/main/scala/TinyGPU.scala:67:22, src/main/scala/rawFloatFromFN.scala:45:19, :48:30
  wire [3:0]  addRecFN_io_a_rawIn_normDist =
    add_a[9]
      ? 4'h0
      : add_a[8]
          ? 4'h1
          : add_a[7]
              ? 4'h2
              : add_a[6]
                  ? 4'h3
                  : add_a[5]
                      ? 4'h4
                      : add_a[4]
                          ? 4'h5
                          : add_a[3] ? 4'h6 : add_a[2] ? 4'h7 : {3'h4, ~(add_a[1])};	// src/main/scala/TinyGPU.scala:67:22, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/primitives.scala:91:52, src/main/scala/rawFloatFromFN.scala:46:21
  wire [24:0] _addRecFN_io_a_rawIn_subnormFract_T =
    {15'h0, add_a[9:0]} << addRecFN_io_a_rawIn_normDist;	// src/main/scala/TinyGPU.scala:67:22, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/rawFloatFromFN.scala:46:21, :52:33
  wire [5:0]  _addRecFN_io_a_rawIn_adjustedExp_T_4 =
    (addRecFN_io_a_rawIn_isZeroExpIn
       ? {2'h3, ~addRecFN_io_a_rawIn_normDist}
       : {1'h0, add_a[14:10]}) + {4'h4, addRecFN_io_a_rawIn_isZeroExpIn ? 2'h2 : 2'h1};	// src/main/scala/TinyGPU.scala:17:7, :67:22, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14
  wire [2:0]  _addRecFN_io_a_T_1 =
    addRecFN_io_a_rawIn_isZeroExpIn & ~(|(add_a[9:0]))
      ? 3'h0
      : _addRecFN_io_a_rawIn_adjustedExp_T_4[5:3];	// src/main/scala/TinyGPU.scala:67:22, src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, src/main/scala/recFNFromFN.scala:48:{15,50}
  wire        addRecFN_io_b_rawIn_isZeroExpIn = add_b[14:10] == 5'h0;	// src/main/scala/TinyGPU.scala:68:22, src/main/scala/rawFloatFromFN.scala:45:19, :48:30
  wire [3:0]  addRecFN_io_b_rawIn_normDist =
    add_b[9]
      ? 4'h0
      : add_b[8]
          ? 4'h1
          : add_b[7]
              ? 4'h2
              : add_b[6]
                  ? 4'h3
                  : add_b[5]
                      ? 4'h4
                      : add_b[4]
                          ? 4'h5
                          : add_b[3] ? 4'h6 : add_b[2] ? 4'h7 : {3'h4, ~(add_b[1])};	// src/main/scala/TinyGPU.scala:68:22, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/primitives.scala:91:52, src/main/scala/rawFloatFromFN.scala:46:21
  wire [24:0] _addRecFN_io_b_rawIn_subnormFract_T =
    {15'h0, add_b[9:0]} << addRecFN_io_b_rawIn_normDist;	// src/main/scala/TinyGPU.scala:68:22, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/rawFloatFromFN.scala:46:21, :52:33
  wire [5:0]  _addRecFN_io_b_rawIn_adjustedExp_T_4 =
    (addRecFN_io_b_rawIn_isZeroExpIn
       ? {2'h3, ~addRecFN_io_b_rawIn_normDist}
       : {1'h0, add_b[14:10]}) + {4'h4, addRecFN_io_b_rawIn_isZeroExpIn ? 2'h2 : 2'h1};	// src/main/scala/TinyGPU.scala:17:7, :68:22, src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14
  wire [2:0]  _addRecFN_io_b_T_1 =
    addRecFN_io_b_rawIn_isZeroExpIn & ~(|(add_b[9:0]))
      ? 3'h0
      : _addRecFN_io_b_rawIn_adjustedExp_T_4[5:3];	// src/main/scala/TinyGPU.scala:68:22, src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, src/main/scala/recFNFromFN.scala:48:{15,50}
  reg  [15:0] add_result;	// src/main/scala/TinyGPU.scala:81:27
  always @(posedge clock) begin	// src/main/scala/TinyGPU.scala:17:7
    if (reset) begin	// src/main/scala/TinyGPU.scala:17:7
      example_data <= 32'h0;	// src/main/scala/TinyGPU.scala:30:29
      example_interrupt <= 1'h0;	// src/main/scala/TinyGPU.scala:53:34
      last_ui_in_6 <= 1'h0;	// src/main/scala/TinyGPU.scala:54:29
      add_a <= 16'h0;	// src/main/scala/TinyGPU.scala:67:22
      add_b <= 16'h0;	// src/main/scala/TinyGPU.scala:68:22
      add_result <= 16'h0;	// src/main/scala/TinyGPU.scala:81:27
    end
    else begin	// src/main/scala/TinyGPU.scala:17:7
      if (_io_data_out_T & io_data_write_n == 2'h2)	// src/main/scala/TinyGPU.scala:17:7, :37:{17,28,47}
        example_data <= io_data_in;	// src/main/scala/TinyGPU.scala:30:29
      else if (_io_data_out_T & io_data_write_n == 2'h1)	// src/main/scala/TinyGPU.scala:17:7, :37:17, :39:{28,47}
        example_data <= {example_data[31:16], io_data_in[15:0]};	// src/main/scala/TinyGPU.scala:30:29, :39:{66,79,99}
      else if (_io_data_out_T & io_data_write_n == 2'h0)	// src/main/scala/TinyGPU.scala:17:7, :37:17, :41:{28,47}
        example_data <= {example_data[31:8], io_data_in[7:0]};	// src/main/scala/TinyGPU.scala:30:29, :41:{66,79,98}
      example_interrupt <=
        io_ui_in[6] & ~last_ui_in_6
        | ~(io_address == 6'h8 & io_data_write_n != 2'h3 & io_data_in[0])
        & example_interrupt;	// src/main/scala/TinyGPU.scala:17:7, :53:34, :54:29, :56:{16,20,23,38}, :57:23, :58:{25,36,55,67,80,93}, :59:23
      last_ui_in_6 <= io_ui_in[6];	// src/main/scala/TinyGPU.scala:54:29, :56:16
      add_a <= example_data[31:16];	// src/main/scala/TinyGPU.scala:30:29, :39:79, :67:22
      add_b <= example_data[15:0];	// src/main/scala/TinyGPU.scala:30:29, :68:22, :70:24
      add_result <= _addRecFN_io_out[15:0];	// src/main/scala/TinyGPU.scala:74:24, :81:27, :82:14
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/TinyGPU.scala:17:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/TinyGPU.scala:17:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/TinyGPU.scala:17:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// src/main/scala/TinyGPU.scala:17:7
    initial begin	// src/main/scala/TinyGPU.scala:17:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/TinyGPU.scala:17:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/TinyGPU.scala:17:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/TinyGPU.scala:17:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/TinyGPU.scala:17:7
        end	// src/main/scala/TinyGPU.scala:17:7
        example_data = _RANDOM[2'h0];	// src/main/scala/TinyGPU.scala:17:7, :30:29
        example_interrupt = _RANDOM[2'h1][0];	// src/main/scala/TinyGPU.scala:17:7, :53:34
        last_ui_in_6 = _RANDOM[2'h1][1];	// src/main/scala/TinyGPU.scala:17:7, :53:34, :54:29
        add_a = _RANDOM[2'h1][17:2];	// src/main/scala/TinyGPU.scala:17:7, :53:34, :67:22
        add_b = {_RANDOM[2'h1][31:18], _RANDOM[2'h2][1:0]};	// src/main/scala/TinyGPU.scala:17:7, :53:34, :68:22
        add_result = _RANDOM[2'h2][21:6];	// src/main/scala/TinyGPU.scala:17:7, :68:22, :81:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/TinyGPU.scala:17:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/TinyGPU.scala:17:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  AddRecFN addRecFN (	// src/main/scala/TinyGPU.scala:74:24
    .io_a
      ({add_a[15],
        _addRecFN_io_a_T_1[2:1],
        _addRecFN_io_a_T_1[0] | (&(_addRecFN_io_a_rawIn_adjustedExp_T_4[5:4]))
          & (|(add_a[9:0])),
        _addRecFN_io_a_rawIn_adjustedExp_T_4[2:0],
        addRecFN_io_a_rawIn_isZeroExpIn
          ? {_addRecFN_io_a_rawIn_subnormFract_T[8:0], 1'h0}
          : add_a[9:0]}),	// src/main/scala/TinyGPU.scala:67:22, src/main/scala/rawFloatFromFN.scala:44:18, :46:21, :48:30, :49:34, :52:{33,46,64}, :57:9, :61:{32,57}, :64:28, :70:33, src/main/scala/recFNFromFN.scala:48:{15,76}, :50:{23,41}
    .io_b
      ({add_b[15],
        _addRecFN_io_b_T_1[2:1],
        _addRecFN_io_b_T_1[0] | (&(_addRecFN_io_b_rawIn_adjustedExp_T_4[5:4]))
          & (|(add_b[9:0])),
        _addRecFN_io_b_rawIn_adjustedExp_T_4[2:0],
        addRecFN_io_b_rawIn_isZeroExpIn
          ? {_addRecFN_io_b_rawIn_subnormFract_T[8:0], 1'h0}
          : add_b[9:0]}),	// src/main/scala/TinyGPU.scala:68:22, src/main/scala/rawFloatFromFN.scala:44:18, :46:21, :48:30, :49:34, :52:{33,46,64}, :57:9, :61:{32,57}, :64:28, :70:33, src/main/scala/recFNFromFN.scala:48:{15,76}, :50:{23,41}
    .io_out (_addRecFN_io_out)
  );	// src/main/scala/TinyGPU.scala:74:24
  assign io_uo_out = example_data[7:0] + io_ui_in;	// src/main/scala/TinyGPU.scala:17:7, :30:29, :47:{28,35}
  assign io_data_out =
    _io_data_out_T
      ? example_data
      : io_address == 6'h4
          ? {24'h0, io_ui_in}
          : io_address == 6'h8 ? {add_result, 16'h0} : 32'h0;	// src/main/scala/TinyGPU.scala:17:7, :30:29, :37:17, :81:27, :89:{17,44}, :90:{17,35}, src/main/scala/chisel3/util/Mux.scala:130:16
  assign io_data_ready = 1'h1;	// src/main/scala/TinyGPU.scala:17:7
  assign io_user_interrupt = example_interrupt;	// src/main/scala/TinyGPU.scala:17:7, :53:34
endmodule

